-- Sabuj Diganta Multimedia: secure public/admin schema
-- Run this SQL in the Supabase SQL Editor for project cnngqlfnexlcddynezwk.

create table if not exists public.employees (
  id text primary key,
  name text not null,
  position text,
  department text,
  phone text,
  email text,
  photo text,
  bio text,
  skills text,
  status text default 'Active',
  is_public boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.recognitions (
  id bigint generated by default as identity primary key,
  employee_id text references public.employees(id) on delete cascade,
  date date,
  title text not null,
  description text,
  proof text,
  video text,
  comment text,
  is_public boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz default now()
);

create table if not exists public.reactions (
  id bigint generated by default as identity primary key,
  reaction text not null,
  created_at timestamptz default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  comment text not null,
  is_public boolean default true,
  created_at timestamptz default now()
);

alter table public.employees enable row level security;
alter table public.recognitions enable row level security;
alter table public.messages enable row level security;
alter table public.reactions enable row level security;
alter table public.comments enable row level security;

-- Recreate policies so old permissive policies cannot leave profile writes open.
drop policy if exists "public read employees" on public.employees;
drop policy if exists "admin insert employees" on public.employees;
drop policy if exists "admin update employees" on public.employees;
drop policy if exists "admin delete employees" on public.employees;
drop policy if exists "public read recognitions" on public.recognitions;
drop policy if exists "admin insert recognitions" on public.recognitions;
drop policy if exists "admin update recognitions" on public.recognitions;
drop policy if exists "admin delete recognitions" on public.recognitions;
drop policy if exists "public insert messages" on public.messages;
drop policy if exists "admin read messages" on public.messages;
drop policy if exists "public insert reactions" on public.reactions;
drop policy if exists "public read reactions" on public.reactions;
drop policy if exists "admin read reactions" on public.reactions;
drop policy if exists "public read comments" on public.comments;
drop policy if exists "public insert comments" on public.comments;
drop policy if exists "admin update comments" on public.comments;
drop policy if exists "admin delete comments" on public.comments;

create policy "public read employees" on public.employees
for select using (is_public = true);
create policy "admin insert employees" on public.employees
for insert with check ((auth.jwt() ->> 'email') = 'mrboka7010@gmail.com');
create policy "admin update employees" on public.employees
for update using ((auth.jwt() ->> 'email') = 'mrboka7010@gmail.com')
with check ((auth.jwt() ->> 'email') = 'mrboka7010@gmail.com');
create policy "admin delete employees" on public.employees
for delete using ((auth.jwt() ->> 'email') = 'mrboka7010@gmail.com');

create policy "public read recognitions" on public.recognitions
for select using (is_public = true);
create policy "admin insert recognitions" on public.recognitions
for insert with check ((auth.jwt() ->> 'email') = 'mrboka7010@gmail.com');
create policy "admin update recognitions" on public.recognitions
for update using ((auth.jwt() ->> 'email') = 'mrboka7010@gmail.com')
with check ((auth.jwt() ->> 'email') = 'mrboka7010@gmail.com');
create policy "admin delete recognitions" on public.recognitions
for delete using ((auth.jwt() ->> 'email') = 'mrboka7010@gmail.com');

create policy "public insert messages" on public.messages
for insert with check (true);
create policy "admin read messages" on public.messages
for select using ((auth.jwt() ->> 'email') = 'mrboka7010@gmail.com');

create policy "public insert reactions" on public.reactions
for insert with check (true);
create policy "public read reactions" on public.reactions
for select using (true);
create policy "admin read reactions" on public.reactions
for select using ((auth.jwt() ->> 'email') = 'mrboka7010@gmail.com');

create policy "public read comments" on public.comments
for select using (is_public = true);
create policy "public insert comments" on public.comments
for insert with check (true);
create policy "admin update comments" on public.comments
for update using ((auth.jwt() ->> 'email') = 'mrboka7010@gmail.com')
with check ((auth.jwt() ->> 'email') = 'mrboka7010@gmail.com');
create policy "admin delete comments" on public.comments
for delete using ((auth.jwt() ->> 'email') = 'mrboka7010@gmail.com');
